#!/bin/bash

chmod +x ./scripts/pre-commit
chmod +x ./scripts/pre-push
chmod +x ./scripts/test
chmod +x ./scripts/coverage
chmod +x ./scripts/clean
chmod +x ./scripts/lint
chmod +x ./scripts/format
chmod +x ./scripts/install

if [[ "$(uname -s)" == "MINGW"* ]]; then
  python.exe -m pip install --upgrade pip
else
  pip install --upgrade pip
fi
echo -e "\e[33mInstalling project dependencies\e[0m"
pip install poetry
poetry install


./scripts/pre-commit
./scripts/pre-push

echo -e "\e[32mDevelopment environment ready!\e[0m"
